### PR TITLE
Rename Country to Region

### PR DESCRIPTION
**Pull request by miniBill**
This is a draft until #2 gets merged.

When #2 is merged, this will be rebased and will only include the last commit

### CODE REVIEW

**Comment by miniBill** [comment]
@dillonkearns rebased and ready for review!

**Comment by dillonkearns** [comment]
Great! I added a CHANGELOG.md file. Would you mind adding notes for #2 and #3 in the Changed and Added sections under 2.0.0? There are some new features, and more importantly some breaking API changes with some subtle design decisions that users will need to understand, so this document would be very useful.

Once we have those notes this looks good to go to me! Thanks again for your work on this 🙏

**Comment by miniBill** [comment]
Will do! Not sure what you mean by "subtle design decisions"? You mean the difference between `parseBcp47` and `parseLanguageTag`?

**Comment by dillonkearns** [comment]
The ones I had in mind were:

- `Country` -> `Region` (some users may be confused at why this changed, and what the implications are for their code and how to upgrade). Something similar to your comment here would be helpful: https://github.com/dillonkearns/elm-bcp47-language-tag/pull/2#issuecomment-1703109748.
- Some types have been moved from opaque types to type aliases pointing to an internal opaque type (Variant, Script, Language, ExtendedLanguage, Country)
- `LanguageTag.Options` renamed `extendedLanguage` to `extensions`, and added `privateUse`
- Added module `LanguageTag.PrivateUse`
- New parser functionality in LanguageTag.Parser
- Added `toParts` and `toSegments` (describe a bit about the purpose of adding those)

**Comment by miniBill** [comment]
Added the info in the `CHANGELOG`

**Comment by miniBill** [comment]
*poke*

**Comment by dillonkearns** [comment]
Thanks so much for your work on this @miniBill! I'm on paternity leave so apologies if I'm slow to respond, but wanted to push this through so it doesn't get too stale.

**Comment by miniBill** [comment]
No worries! You definitely have higher priorities :)

**Pull request merged**
